# Site settings
title: Rithvin Koneru
general_email: rithvin16@gmail.com
academic_email: rithvink@terpmail.umd.edu

description: > # this means to ignore newlines until "baseurl:"
  I'm a University of Maryland Computer Science major and business minor interested in artifical intelligence, data science, and finance.
  Feel free to contact me through email or LinkedIn.

baseurl: "" # the subpath of your site, e.g. /blog/

url: "https://rithvink.github.io/" # the base hostname & protocol for your site

# twitter_username: jekyllrb
github_username: RithvinK
linkedin_username: rithvin-koneru
#facebook_username: facebook_username
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
# permalink: blog/:year/:month/:title
