# Site settings
title: Aryan Mittal
general_email: thearyanmittal@gmail.com
academic_email: aryan.mittal@gatech.edu

description: > # this means to ignore newlines until "baseurl:"
  I'm a Georgia Tech Mathematics and Computer Science student interested in combinatorics, game theory, and data science.
  Feel free to contact me via email or LinkedIn.

baseurl: "" # the subpath of your site, e.g. /blog/

url: "http://www.thearyanmittal.com/" # the base hostname & protocol for your site

# twitter_username: jekyllrb
github_username: thearyanmittal
linkedin_username: thearyanmittal
#facebook_username: facebook_username
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
# permalink: blog/:year/:month/:title